version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Giảm từ 1GB xuống 512MB
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: 262144
        hard: 262144
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 1GB # Giới hạn memory tối đa
          cpus: '1.0' # Giới hạn CPU
        reservations:
          memory: 512MB # Memory tối thiểu được đảm bảo
          cpus: '0.5' # CPU tối thiểu được đảm bảo
volumes:
  es_data:


networks:
  app-network:
    driver: bridge
